wypozyczalnia_test_annotations:
    resource: "@WypozyczalniaTestBundle/Controller"
    type: annotation

wypozyczalnia_test_homepage:
    pattern: /
    defaults:
        _controller: WypozyczalniaTestBundle:Wypozyczalnia:index
           
        