services:
    wypozyczalania.registration.form.type:
        class: Wypozyczalnia\TestBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: wypozyczalnia_user_registration }